### ISSUE TITLE
nuxt-icons doesn't work in rc versions of nuxt3

### ISSUE THREAD

**Issue by PlayerValley** [gitFoxCode/nuxt-icons#11]
tried installing it on nuxtjs 3.0.0-rc.9, this occurs:

 WARN  Module nuxt-icons is disabled due to incompatibility issues:                                                  10:44:03  
 - [nuxt] Nuxt version `^3.0.0` is required but currently using `3.0.0-rc.9`

**Comment by durbanitas** [comment]
got the same issue

**Comment by luabraggion** [comment]
I'm also having the same problem

**Comment by gitFoxCode** [comment]
@PlayerValley @durbanitas @luabraggion Now everything should work, If any further problems arise please write the issue again and then I will deal with solving it more deeply, unfortunately due to lack of time I will only be able to deal with this module at full speed from October onwards

**Comment by complianceux001** [comment]
> @PlayerValley @durbanitas @luabraggionAgora tudo deve funcionar, se surgirem mais problemas, por favor, escreva o problema novamente e então tratarei de resolvê-lo mais profundamente, infelizmente, devido à falta de tempo, só poderei lidar com este módulo a toda velocidade a partir de outubro

thank you so much..

**Comment by luabraggion** [comment]
I still have the same error I have version 2.0.2 I looked there is no more.

 �

WARN  autoImports:extend hook is deprecated. Use addImports() from @nuxt/kit or imports:extend with nuxt>=3.0.0-rc.9.

 �

**Comment by gitFoxCode** [comment]
@luabraggion Only a message appears, or the whole module does not work? I will solve the problem with this 'autoImports:extend' in the next larger update until then, the message may occur, but it will not affect applications

**Comment by luabraggion** [comment]
the whole module doesn't work and that's why it gives an error in the application I can't even upload the application anymore because of that

 �
