### ISSUE TITLE
Use the stroke-width issue 

### ISSUE THREAD

**Issue by impohcom** [gitFoxCode/nuxt-icons#12]
![image](https://user-images.githubusercontent.com/90586970/192953557-f08eb2f6-df5a-4f71-9804-191456fc4d1e.png)

The stroke-width attribute is filtered out

**Comment by gitcetop** [comment]
Before use
```html
<svg viewBox="0 0 1024 1024" width="30" height="40">
  <path fill="none" stroke-linejoin="round" stroke-linecap="round" stroke-width="145.067" stroke="currentColor"
    d="m341.333 170.667 341.334 341.332-341.334 341.335"></path>
</svg>
```

after use
```html
<svg viewBox="0 0 1024 1024" width="30" height="40">
  <path fill="none" stroke-linejoin="round" stroke-linecap="round" stroke-="145.067" stroke="currentColor"
    d="m341.333 170.667 341.334 341.332-341.334 341.335"></path>
</svg>
```

**Comment by gitFoxCode** [comment]
Thanks for your message, I will fix this in the latest version I will be working on from October

**Comment by gitFoxCode** [comment]
@impohcom New version on nuxt 3.0.0 is already available, your problem should disappear, if still something is wrong please write another issue
