### ISSUE TITLE
Name prop format

### ISSUE THREAD

**Issue by szulcus** [gitFoxCode/nuxt-icons#13]
Is it possible to change the name format? In the project I use kebab-case for svg icons and it looks quite strange. So far, I have used the format preferred by [@nuxtjs/svg-sprite](https://www.npmjs.com/package/@nuxtjs/svg-sprite) (e.g: "fa/ban-solid"). It would be nice to be able to use something similar here.
![image](https://user-images.githubusercontent.com/48328739/194604039-3755ff2f-fc8a-4edc-9148-cf1e7c2f1c40.png)
![image](https://user-images.githubusercontent.com/48328739/194603784-e9445be7-705b-46e1-b38e-8bc921be7b2b.png)

**Comment by gitFoxCode** [comment]
In the next version, the naming will be changed to `nuxt-icon name="fa/ban-solid` (this version is practically ready, I'm just waiting for some feedback from people higher up in nuxt). Should appear in days

**Comment by szulcus** [comment]
> In the next version, the naming will be changed to `nuxt-icon name="fa/ban-solid"` (this version is practically ready, I'm just waiting for some feedback from people higher up in nuxt). Should appear in days

Thank you for your quick reply. I just edited the issue and added a few more sentences. Will this be fixed in a future release?

**Comment by gitFoxCode** [comment]
@szulcus This is not an expected occurrence, you should be able to use the `<nuxt-icon name="arrow-left">`

**Comment by szulcus** [comment]
Sorry, everything is working fine. I thought I needed to write `Arrow-left` or `ArrowLeft`, but `arrow-left` works. Have a nice weekend, greetings from Poland 😁

**Comment by gitFoxCode** [comment]
@szulcus Nie ma sprawy, też jestem z Polski i też jestem studentem 😁

**Comment by gitFoxCode** [comment]
@szulcus Najnowsza wersja na Nuxt 3.0.0 już jest dostępna i zawiera zmianę o którą pytałeś, zachęcam do testowania i w razie czego stwórz nowy issue, dużo zmian wprowadziłem w tym module i potrzebuję feedbacku jeżeli coś nie będzie działać

**Comment by szulcus** [comment]
Dzięki, jesteś wielki! ❤️ Przy okazji, jeśli już mam możliwość pisać po polsku, zapytam o coś 😅. Jestem obecnie na konferencji Nuxt Nation i padł pomysł na połączenie sił razem z modułem `nuxt-icon`. Co o tym sądzisz?
![image](https://user-images.githubusercontent.com/48328739/202493581-a6f02905-1f59-4116-bff4-83081dd3c6bf.png)
