### ISSUE TITLE
Prop type failed for prop "name"

### ISSUE THREAD

**Issue by meleshkevich** [gitFoxCode/nuxt-icons#15]
Hi there, thanks for great work!
Just want to ask if there is possibility to specify type props for name, since using conditional icon rendering with 
`    <nuxt-icon
              :name="[
                SomeCondition
                  ? `IconName-1`
                  : `IconName-2`,
              ]"`
getting errors in console.
Of course there are workarounds for that, but I am just curioous, if prop types could be somehow specified for name. 
Thank you!

**Comment by gitFoxCode** [comment]
Hi, sorry for the late reply, of course it is possible to use, but not as arrays:
` <nuxt-icon :name="someCondition === true ? 'myiconnameiftrue' : 'myiconnameiffalse'" />`
