### ISSUE TITLE
[unimport] failed to find "NuxtIcons" imported from "#imports"

### ISSUE THREAD

**Issue by shba007** [gitFoxCode/nuxt-icons#19]
Upgrading from Nuxt@RC13 to Nuxt@RC14 Causes this error

[unimport] failed to find "NuxtIcons" imported from "#imports"

**Comment by gitFoxCode** [comment]
Hi, today I will make a release (it will work on RC-14) that changes the module a bit and fixes all the bugs, I still just need to test it on all sides :D
