### ISSUE TITLE
Module improvement suggestions

### ISSUE THREAD

**Issue by pi0** [gitFoxCode/nuxt-icons#2]
Hi! Some small things i've noticed in module can be improved:

- Please use a fixed version of `@nuxt/kit` in dependencies and not edge! (https://github.com/gitFoxCode/nuxt-icons/blob/00f7903e9ced6d4963cfba0650ad639fbd941bc1/package.json#L36). It can be like `"3.0.0-rc.2"`
- There is a leftover `addPlugin` option remaining from template (https://github.com/gitFoxCode/nuxt-icons/blob/00f7903e9ced6d4963cfba0650ad639fbd941bc1/src/module.ts#L5)
- We have `addAutoImports` utility from kit as well :) 
- (just heads up) Signigurare of `resolveFiles` from kit might be changed before `3.0.0` release.

**Comment by gitFoxCode** [comment]
Thanks for the feedback! I corrected the issues. I will have to check `addAutoImports` utility and maybe I will use it in the next version. "Signigurare of resolveFiles" will be in the back of my mind 😄
