### ISSUE TITLE
ERROR [unimport] failed to find "NuxtIcons" imported from "#imports"

### ISSUE THREAD

**Issue by DevShaded** [gitFoxCode/nuxt-icons#20]
Tried to use a custom SVG icon with 

```html
<nuxt-icon name="bell"></nuxt-icon>
```

Nuxt returns with error
```js
[vite] Internal server error: [unimport] failed to find "NuxtIcons" imported from "#imports"
  Plugin: nuxt:imports-transform
  File: /node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue
```

**Comment by durbanitas** [comment]
got the same issue. Updated nuxt from `"nuxt": "^3.0.0-rc.8"` to `"nuxt": "^3.0.0-rc.14"`

**Comment by gitFoxCode** [comment]
Tomorrow I'm releasing nuxt-icons v3.0.0, all such bugs should be fixed - even on nuxt's most recent versions

**Comment by DevShaded** [comment]
Thank you @gitFoxCode! The plugin works great!
