### ISSUE TITLE
[feature request] Ability to define default properties for the `nuxt-icon` component

### ISSUE THREAD

**Issue by szulcus** [gitFoxCode/nuxt-icons#24]
**Describe**
I think it would be nice to give this option to users in the configuration for the module. For example, for the `:filled="true"` property, my icons often break like this:
![image](https://user-images.githubusercontent.com/48328739/202706269-3bda5be2-ef3e-4556-9d87-4040b99ee1d9.png)
⬇️
![image](https://user-images.githubusercontent.com/48328739/202706005-a8991699-dae9-48e1-905b-960fc51e1ac9.png)

More complex svg's often require me to manually set the `fill="currentColor"` attribute. It would be much more convenient if I didn't have to define the `filled` property every time when I use this component.

**Comment by gitFoxCode** [comment]
@szulcus Hi, could you please send the SVG code of these icons so I can work on it?

**Comment by szulcus** [comment]
@gitFoxCode Of course. These icons are from a designer from my work, but I quickly created something for testing:
![image](https://user-images.githubusercontent.com/48328739/202708001-03fb6b95-2177-4c3f-bdf7-393f2f9d0177.png)
![image](https://user-images.githubusercontent.com/48328739/202708019-aa3da908-e616-4cb5-a02c-ea04e6678398.png)
```html
<svg xmlns="http://www.w3.org/2000/svg" width="14.4" height="14.948" viewBox="0 0 14.4 14.948">
  <path id="test-icon" d="M17.813,5.129H5.425l-.01,12.948H17.8Zm-6.2,9.925A3.451,3.451,0,1,1,15.065,11.6,3.461,3.461,0,0,1,11.614,15.055Z" transform="translate(-4.414 -4.129)" fill="none" stroke="currentColor" stroke-width="2"/>
</svg>
```

**Comment by gitFoxCode** [comment]
@szulcus You would like the module to have the ability to set each icon to have a filled effect as default?
Something like `modules: [['nuxt-icons', { default: 'filled' }]]`?

**Comment by szulcus** [comment]
@gitFoxCode chia like this, although I'd prefer something like this:
```ts
interface Options {
    defaults: {
        filled: boolean;
        // Other properties
    };
}
```
Thanks!

**Comment by DanyAtanov** [comment]
![image](https://user-images.githubusercontent.com/74001807/202859057-706c3b28-1e20-4f55-9918-89f46052238b.png)

![image](https://user-images.githubusercontent.com/74001807/202859080-e16e702d-6b56-49a3-b276-ffe179702247.png)

**Comment by szulcus** [comment]
@DanyAtanov use `filled` prop

**Comment by DanyAtanov** [comment]
O, thank you, missed this part =) Hope soon I can change default fill option, cause most my icons didnt need it.

**Comment by gitFoxCode** [comment]
@szulcus @DanyAtanov Ok, you are right, there should be such an option available, I will add it in the next update
