### ISSUE TITLE
Issue with coloring in some cases

### ISSUE THREAD

**Issue by jesspinklet** [gitFoxCode/nuxt-icons#29]
I have download a direct SVG file from [phosphor](https://phosphoricons.com/) icon and the SVG file itself seams straight forward. In my case it was airplane-tilt icon.

However I cant color it correctly. It will only add a new background color behind the Icon.
Not sure if I'm missing something in here.

**Comment by gitFoxCode** [comment]
@jesspinklet Actually, icons that have a certain stroke behave badly. I will work on this in future versions of the module. For now, you can get around this by changing the stroke directly in the SVG file:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="192" height="192" fill="#000000" viewBox="0 0 256 256">
<path d="M209.5,80.4,175.9,112l32,88-24,24-47.8-70-24.2,22v24l-24,24L73.7,182.1,31.9,168l24-24h24l24-24-72-48,24-24,88,32,31.7-33.5-.7.5a24,24,0,0,1,34,34Z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="16"></path>
</svg>
```
