### ISSUE TITLE
Non existing icon causes whole page to fail

### ISSUE THREAD

**Issue by HerrZatacke** [gitFoxCode/nuxt-icons#32]
**Describe the bug**
Non existing icon causes whole page to fail. SSR fails with `errorLog.ts:4 iconsImport[props.name] is not a function`

**To Reproduce**
install version 3.0.0 of nuxt-icons
```
<nuxt-icon name="something-which-does-not-exist" />
```

**Expected behavior**
The behavior of version 2.x was fine where instead of an icon some text "undefined" was shown
It seems the issue has already been fixed with [this commit](https://github.com/gitFoxCode/nuxt-icons/commit/4425862dc222a4627db474a4104936a243cd75db) but it seems it has not been published to npm.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any (error happens server-side as well, tested in node version 16.17.0)
 - Version: nuxt-icons@3.0.0

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser: any
 - Version: nuxt-icons@3.0.0

**Additional context**

**Comment by gitFoxCode** [comment]
Problem fixed in version 3.1.0
