### ISSUE TITLE
Add stroke parametr

### ISSUE THREAD

**Issue by javascriptninjazxc** [gitFoxCode/nuxt-icons#35]
add please stroke parametr!!!!

**Comment by javascriptninjazxc** [comment]
I added it with my own hands, but I didn't want to lose it every time I updated. So please be kind enough to add it as well!

**Comment by gitFoxCode** [comment]
@javascriptninjazxc In what sense of stroke parameter? How would you like the linear icons to behave and what syntax would be best?

**Comment by gitFoxCode** [comment]
Now for icons that have "stroke" the color also changes
