### ISSUE TITLE
Icons aren't rendered on the SSR

### ISSUE THREAD

**Issue by szobX** [gitFoxCode/nuxt-icons#39]
**Describe the bug**
Icons in <nuxt-icon> wrapper aren't rendered  on the SSR 

**To Reproduce**
typical use NuxtIcon component. (client-only is not used anywhere above)
```js
  <button
            aria-describedby="cart"
        >
            <NuxtIcon name="cart" filled class="text-2xl lg:text-3xl relative" aria-hidden="true" />
            <span
                v-if="isFull"
                class="w-[7px] h-[7px] bg-green block rounded-full absolute top-0 -right-0.5 lg:top-1"
                aria-hidden="true"
            />
        </button>
```
**Expected behavior**
Icons  should render at ssr  

**Screenshots**
Screen from SSR preview ( extension for chrome)
![image](https://user-images.githubusercontent.com/24682055/227552742-d9a2d9d0-0ce3-4980-a0b2-310e0a123ba4.png)

After render all
![image](https://user-images.githubusercontent.com/24682055/227553108-89b24ff2-9fe6-49e3-9141-6c3cef0192b7.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Browser Brave/Chrome

**Additional context**

**Comment by MathiasOxholm** [comment]
Experiencing the same issue here. This results in layout shift on the webshop I'm currently developing

**Comment by Aira-Sakuranomiya** [comment]
Same problem here.

**Comment by gitFoxCode** [comment]
@Aira-Sakuranomiya @MathiasOxholm @szobX I made a new version, check if the problem still occurs and if there are any other problems - from now on icons with `stroke` are detected automatically and their stroke color is matched to the text color which may affect projects where someone tried to circumvent this problem using CSS

**Comment by szobX** [comment]
@gitFoxCode  after upgrade package to latest works perfectly! thx

**Comment by jasonhibbs** [comment]
fixed for me!
