### ISSUE TITLE
icons not rendered correctly with nuxt-icon

### ISSUE THREAD

**Issue by TobiasDoe** [gitFoxCode/nuxt-icons#43]
When I use this Icon with nuxt-icon it doesn't render correctly 

![image](https://github.com/gitFoxCode/nuxt-icons/assets/2061395/69e5b34c-c6bf-49f2-a62e-9ac894dc1532)

Svg:
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="10" height="10" viewBox="0 0 10 10">
    <defs>
        <path id="a" d="M2.69 1.019H.057v.424H2.69c.101.469.497.827.997.827.497 0 .896-.358.996-.827h3.126v-.424H4.683a1.025 1.025 0 0 0-.996-.827c-.499 0-.895.358-.997.827z"/>
        <path id="c" d="M5.85 1.749H.018v.424H5.85c.099.468.498.828.995.828a1.04 1.04 0 0 0 0-2.08c-.497 0-.896.359-.995.828z"/>
        <path id="e" d="M5.831 1.262H0v.423h5.831c.099.47.498.828.995.828a1.04 1.04 0 0 0 1.04-1.039c0-.574-.467-1.04-1.04-1.04-.497 0-.896.359-.995.828z"/>
    </defs>
    <g fill="none" fill-rule="evenodd">
        <g transform="translate(1 3.566)">
            <mask id="b" fill="#fff">
                <use xlink:href="#a"/>
            </mask>
            <path fill="#14D719" d="M-4.943 7.27h17.752V-4.808H-4.943z" mask="url(#b)"/>
        </g>
        <g transform="translate(1 5.566)">
            <mask id="d" fill="#fff">
                <use xlink:href="#c"/>
            </mask>
            <path fill="#14D719" d="M-4.981 8h17.866V-4.079H-4.981z" mask="url(#d)"/>
        </g>
        <g transform="translate(1 .566)">
            <mask id="f" fill="#fff">
                <use xlink:href="#e"/>
            </mask>
            <path fill="#14D719" d="M-5 7.513h17.866V-4.566H-5z" mask="url(#f)"/>
        </g>
    </g>
</svg>
```

**Expected behavior**
here is the same icon just with inline-svg
![image](https://github.com/gitFoxCode/nuxt-icons/assets/2061395/dea0822a-0be9-4b06-a955-128c1a62c642)

**Desktop:**
 - OS: windows
 - Browser: tested all but safari - all have the issue
 - Versions: latest

**Comment by gitFoxCode** [comment]
@TobiasDoe I checked and in my case the icon behaves correctly:
![image](https://github.com/gitFoxCode/nuxt-icons/assets/24279375/3f1d852e-b71d-462a-be73-8b8aa8525acb)
```
<h1><nuxt-icon name="testicon" filled/> Article title</h1>
```
Could you give your code from the .vue file?

**Comment by TobiasDoe** [comment]
@gitFoxCode thanks for the answer and the tip. 

I tried to debug it more, and I found even stranger things.
first I know the icons work correctly when I only have ONE visible.

I got it to work correctly when I go away from "simple" def-ids: 
like from #a to #iconname-a. 
now it shows correctly. 
![image](https://github.com/gitFoxCode/nuxt-icons/assets/2061395/8742d974-69ec-4f57-b797-2a2fbdd09583)

but now things get real crazy: 
I have now 2 of them, in different components. 
![image](https://github.com/gitFoxCode/nuxt-icons/assets/2061395/d707b532-8d0d-4a18-ac6e-0b5df3379d59)

when I hide the first one in the nav-list to the left. 
the second one forgets all his defs. 
![image](https://github.com/gitFoxCode/nuxt-icons/assets/2061395/ab824af7-075a-471b-9faa-1ad192f26a72)

this is really strange to me.

**Comment by ShingLi** [comment]
error rendering svg icon
I had the same question
![image](https://github.com/gitFoxCode/nuxt-icons/assets/17964694/42c535b6-ace8-4767-86f4-26c62599ab3a)
![image](https://github.com/gitFoxCode/nuxt-icons/assets/17964694/0013176e-ed52-43bf-b189-a51eeab079cb)
![image](https://github.com/gitFoxCode/nuxt-icons/assets/17964694/e58a4b06-8511-4ee5-a137-e548fdb4814a)
![image](https://github.com/gitFoxCode/nuxt-icons/assets/17964694/df9106aa-f1c1-426e-8bd1-ce4c666ce751)

**Comment by gitFoxCode** [comment]
@ShingLi Can you send me the source code of the SVG files?

**Comment by ShingLi** [comment]
> @ShingLi Can you send me the source code of the SVG files?

happy to have your reply, 
![password](https://github.com/gitFoxCode/nuxt-icons/assets/17964694/9e83f10a-8cd2-4b54-95b6-33eed43a74ac
![phone](https://github.com/gitFoxCode/nuxt-icons/assets/17964694/811f2b11-9cdc-44e8-964e-b92350c39b59)
)
can you see it?

**Comment by gitFoxCode** [comment]
@ShingLi These icons are unnecessarily complicated, they can be simplified, for example "phone": 
```svg
<svg width="145" height="186" viewBox="0 0 145 186" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M125.4 0C135.8 0 144.3 8.5 144.3 18.9V166.9C144.3 177.3 135.8 185.8 125.4 185.8H18.9C8.5 185.8 0 177.3 0 166.9V18.9C0 8.5 8.5 0 18.9 0H125.4ZM131 130.5H13.4V167C13.4 170 15.8 172.5 18.9 172.5H125.4C128.5 172.5 130.9 170 131 167V130.5ZM82.6 144.8C86.2 144.8 89.2 147.8 89.2 151.5C89.2 155.2 86.2 158.2 82.5 158.2H61.8C58.0997 158.2 55.1 155.2 55.1 151.5C55.1 147.8 58.0997 144.8 61.8 144.8H82.6ZM125.4 13.4H18.9C15.9 13.4 13.4 15.9 13.4 18.9V117H130.9V18.9C130.9 15.9 128.5 13.4 125.4 13.4Z" fill="black"/>
</svg>
```
Your SVG code contains "multiple icons simultaneously" and module doesn't know how to handle it well. For the moment, the best solution to this problem would be to simplify code of these icons, or you can also try using the [nuxt/icon](https://github.com/nuxt-modules/icon) module
