### ISSUE TITLE
Any way to disable the standard css? 

### ISSUE THREAD

**Issue by bartddop** [gitFoxCode/nuxt-icons#46]
Would is be smart to have a setting where you can turn off the standard css ? I know you can overwrite css. But with the fill currentColor it gives me problems with more complex svg's like a logo or one with multiple colors. 

```
.nuxt-icon {
  width: 1em;
  height: 1em;
  margin-bottom: 0.125em;
  vertical-align: middle;
}
.nuxt-icon--fill,
.nuxt-icon--fill * {
  fill: currentColor;
}
```

Thanks for building this package!

**Comment by gitFoxCode** [comment]
Disabling CSS (currentColor) will make SVG icons no longer able to be "colored from text" which would make the module lose its biggest advantage

**Comment by bartddop** [comment]
Oke all good! Than it's not a suitable package for svg's with multiple colors.

**Comment by gitFoxCode** [comment]
@bartddop You can use SVG with multiple colors by using the "filled" attribute: `<nuxt-icon name="test" filled/>`
