### ISSUE TITLE
How can it be loaded on demand?

### ISSUE THREAD

**Issue by cdwmhcc** [gitFoxCode/nuxt-icons#5]
This scheme will write all svg to nuxticons.mjs file, my project has several thousand svg icons, nuxticons.mjs file will be over 5mb.

How can it be loaded on demand?

**Comment by cdwmhcc** [comment]
1. create file `/server/api/getIcon.ts`
2. create file `/components/icon.tsx`

Get the content of the svg icon through the server-side getIcon.ts api.
Render svg icon via component icon.txs.

Are there any downsides to this scheme?

**Comment by cdwmhcc** [comment]
# Another solution

https://stackblitz.com/edit/github-1ck5ek?file=package.json

**Comment by gitFoxCode** [comment]
@cdwmhcc New version on nuxt 3.0.0 is now available, I encourage you to test it 😄

**Comment by cdwmhcc** [comment]
> @cdwmhcc New version on nuxt 3.0.0 is now available, I encourage you to test it 😄

Wow, crazy, I'll test it later 👍👍👍
